const User = require("../models/User");
const jwt = require("jsonwebtoken");
const bcrypt = require("bcrypt");
const crypto = require("crypto");
const transporter = require("../utils/mail");

// Login
const authenticateUser = async (req, res) => {
  try {
    // Get email and password from frontend
    const { email, password } = req.body;
    const user = await User.findOne({ email });

    //CHECKS
    // Check if user exists
    if (!user) {
      return res.status(404).json({
        message: "User Not Found",
      });
    }

    // Check password
    const isMatch = await bcrypt.compare(password, user.password);

    if (!isMatch) {
      // Invalid password
      return res.status(401).json({
        message: "Invalid Password",
      });
    }

    //token genrater
    const token = jwt.sign(
      {
        id: user._id,
        email: user.email,
        role: user.role,
      },
      process.env.JWT_SECRET,
      {
        expiresIn: "0.6h",
      },
    );

    //testing for just
    console.log(process.env.JWT_SECRET);
    console.log(`Token generated by controller: ${token}`);

    // Login successful
    return res.status(200).json({
      message: "Login Successful",
      token: token,
    });
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message: "Server Error",
    });
  }
};

// Register
// Register
const registerUser = async (req, res) => {
  try {
    // Get data from frontend
    const { email, password } = req.body;

    // Check if email already exists
    const existingUser = await User.findOne({ email });

    if (existingUser) {
      return res.status(409).json({
        message: "Email already exists",
      });
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 10);

    // Save user
    const user = new User({
      email,
      password: hashedPassword,
    });

    await user.save();

    res.status(201).json({
      message: "Registration Successful",
    });
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message: "Server Error",
    });
  }
};

const getCurrentUser = async (req, res) => {
  const user = await User.findById(req.user.id);
  if (!user) {
    res.json({ message: "User not exsist" });
  }
  const { email, role } = user;

  res.json({
    email,
    role,
  });
};

const forgotPassword = async (req, res) => {
  try {
    const { email } = req.body;

    // Step 1:
    // Check if user exists
    const user = await User.findOne({ email });
    if (!user) {
      return res.status(404).json({
        message: "User not found",
      });
    }

    const resetToken = crypto.randomBytes(32).toString("hex");
    const resetTokenExpiry = Date.now() + 15 * 60 * 1000;
    user.resetToken = resetToken;
    user.resetTokenExpiry = resetTokenExpiry;

    await user.save();
    
    const resetLink = `http://localhost:5173/reset-password/${resetToken}`;
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: email,
      subject: "Reset link by nodemailar",

      text: `Click the link below to reset your password:${resetLink}`
    });

    return res.json({
      message: "Reset token generated",
      resetToken,
    });
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message: "Something went wrong",
    });
  }
};

const resetPassword = async (req, res) => {
  try {
    const { resetToken, newPassword } = req.body;

    // Find user with valid reset token
    const user = await User.findOne({
      resetToken,
      resetTokenExpiry: { $gt: Date.now() },
    });

    if (!user) {
      return res.status(400).json({
        message: "Invalid or Expired Token",
      });
    }

    // Hash new password
    const hashedPassword = await bcrypt.hash(newPassword, 10);

    // Update password
    user.password = hashedPassword;

    // Clear reset token
    user.resetToken = null;
    user.resetTokenExpiry = null;

    await user.save();

    res.json({
      message: "Password Reset Successfully",
    });
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message: "Something went wrong",
    });
  }
};

module.exports = {
  authenticateUser,
  registerUser,
  getCurrentUser,
  forgotPassword,
  resetPassword,
};
